[package]
authors.workspace    = true
categories.workspace = true
description          = "<DESCRIPTION>"
edition.workspace    = true
homepage.workspace   = true
keywords.workspace   = true
license.workspace    = true
name                 = "pglt_diagnostics"
repository.workspace = true
version              = "0.0.0"


[dependencies]
backtrace                   = "0.3.74"
bpaf                        = { workspace = true }
enumflags2                  = { workspace = true }
pglt_console                = { workspace = true, features = ["serde"] }
pglt_diagnostics_categories = { workspace = true, features = ["serde"] }
pglt_diagnostics_macros     = { workspace = true }
pglt_text_edit              = { workspace = true, features = ["serde"] }
pglt_text_size.workspace    = true
schemars                    = { workspace = true, optional = true }
serde                       = { workspace = true, features = ["derive"] }
serde_json                  = { workspace = true }
termcolor                   = { workspace = true }
unicode-width               = { workspace = true }

[features]
schema = ["dep:schemars", "pglt_text_edit/schema", "pglt_diagnostics_categories/schema", "pglt_console/schema"]

[dev-dependencies]

[lib]
doctest = false
