
[package]
authors.workspace    = true
categories.workspace = true
description          = "<DESCRIPTION>"
edition.workspace    = true
homepage.workspace   = true
keywords.workspace   = true
license.workspace    = true
name                 = "docs_codegen"
repository.workspace = true
version              = "0.0.0"

[dependencies]
regex              = { workspace = true }
toml                     = { workspace = true }
anyhow                     = { workspace = true }
bpaf                     = { workspace = true, features = ["docgen"] }

pglt_configuration = { workspace = true }
pglt_flags = { workspace = true }
pglt_cli = { workspace = true }

