[toolchain]
# The default profile includes rustc, rust-std, cargo, rust-docs, and clippy.
# https://rust-lang.github.io/rustup/concepts/profiles.html
profile = "default"
# For some reason, rustfmt is not included in the default profile. Add it here.
components = ["rustfmt"]
channel = "1.85.0"
