[package]
authors.workspace    = true
categories.workspace = true
description          = "<DESCRIPTION>"
edition.workspace    = true
homepage.workspace   = true
keywords.workspace   = true
license.workspace    = true
name                 = "pg_workspace"
repository.workspace = true
version              = "0.0.0"


[dependencies]
async-std = "1.12.0"
dashmap   = "5.5.3"
text-size = "1.1.1"

pg_base_db.workspace      = true
pg_fs.workspace           = true
pg_hover.workspace        = true
pg_lint.workspace         = true
pg_query_ext.workspace    = true
pg_schema_cache.workspace = true
pg_syntax.workspace       = true

sqlx.workspace            = true
tree-sitter.workspace     = true
tree_sitter_sql.workspace = true

[dev-dependencies]

[lib]
doctest = false

[features]
