name: Publish NPM (Automatic)

on:
  release:
    types: [released, prereleased]

jobs:
  publish_npm:
    uses: ./.github/workflows/publish.reusable.yml
    permissions:
      contents: write
      id-token: write
    with:
      release-tag: ${{ github.event.release.tag_name }}
      is-prerelease: ${{ github.event.release.prerelease }}
    secrets: inherit
